version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: chatgetrol_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatgetrol_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: chatgetrol_backend
    ports:
      - "4000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
  redis:
    image: redis:7
    container_name: chatgetrol_redis
    restart: always
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    container_name: chatgetrol_pgadmin
    restart: always
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
volumes:
  postgres_data:
  